-- phpMyAdmin SQL Dump
-- version 4.5.4.1deb2ubuntu2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Feb 02, 2019 at 09:09 AM
-- Server version: 5.7.17-0ubuntu0.16.04.2
-- PHP Version: 7.0.32-0ubuntu0.16.04.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `cruises`
--

--
-- Dumping data for table `backend_subregion`
--

INSERT INTO `backend_subregion` (`id`, `name`, `description`, `url`, `region_id`, `slug`, `is_active_destination`, `alias`) VALUES
(1, 'Alaska', '<p></p><p class="MsoNormal"><span style="font-family: Arial, sans-serif;"><span style="font-size: 16px;">The capital is Juneau; total area is 591,004 sq. miles. Most of the 550,000 inhabitants of Alaska are of Aleutian, Indian and Eskimom origin; settlers dating back almost 8,000 years. This northernmost US state is a major attraction for the cruise lines; oil and natural gas are the most abundant natural resources.</span></span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Alaska', 1, 'alaska', 1, 'Alaska'),
(2, 'Alaska - Northbound', '<p></p><p class="MsoNormal" style="margin-left: .5in;"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;"><span style="font-family: Arial, sans-serif;"><span style="font-size: 16px;">The nickname for Alaska is the “Final Frontier,” but perhaps no other region embodies this concept as much as the state’s great north. Roughly one third of Alaska’s territory lies above the Arctic Circle, a land of extreme landscapes and untamed beauty. Steep mountain ranges, coastal plains, rugged tundra, and polar habitats thriving with wildlife are some of the natural attractions here, while the native Eskimo culture provides a fascinating element to a region that may otherwise seem unfit for human life. </span><span style="font-size: 12pt;"> </span></span></span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Alaska%20-%20Northbound', 1, 'alaska-northbound', 0, 'Alaska - Northbound'),
(3, 'Alaska - Southbound', '<p></p><p><span style="font-family: Arial, sans-serif;"><span style="font-size: 16px;">Alaska’s rugged, vast natural habitat begs to be explored, a fact that’s perhaps most evident in the state’s southwestern region. Expanding from the Gulf Alaska westward toward Asia by way of the Aleutian Islands, this corner of the largest U.S. state features contrasting sceneries that range from snow-capped mountain ranges and quaint seaside villages to windswept tundra and barren volcanic landscapes. As one of the richest salmon areas in the world, southwest Alaska draws record numbers of wildlife species, as well as travelers eager to unlock all its natural treasures. </span></span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Alaska%20-%20Southbound', 1, 'alaska-southbound', 0, 'Alaska - Southbound'),
(4, 'Alaska - Inside Passage', '<p></p><p class="MsoNormal" style="margin-left: .5in;"><span style="font-family: Arial, sans-serif;"><span style="font-size: 16px;">An extraordinary collection of misty fjords, glaciers, rainforests, countless islands and mountains, the Inside Passage stretches from the coast of Canada’s British Columbia to Alaska’s southeastern panhandle. The landscape of this region was shaped millions of years ago by massive glaciers, and the irregular and jagged nature of these coasts seems tailor-made for exploring aboard a cruise ship. Ports of call here include Juneau, Ketchikan, Skagway, and Petersburg, offering plenty of creature comforts for visitors. But the abundant wildlife is the true star of the Inside Passage and one of the primary reasons to visit this beautiful region.</span></span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Alaska%20-%20Inside%20Passage', 1, 'alaska-inside-passage', 0, 'Alaska - Inside Passage'),
(5, 'Russian Coast', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">Remote, rugged, and stunningly beautiful, the coasts of the Russian Far East are about as off-the-beaten-path as you can get. Covering the North Pacific and crossing beyond the Arctic Circle, the eastern seaboard of Russia is a vast collection of pristine landscapes, jagged mountains, volcanic islands, and lush habitats thriving with Arctic life. Cruise ships call on several ports, including Anadyr, Petropavlosk-Kamchatskiy, and Yuzhno-Sakhalinsk, as well as significant landmarks such as the Bering Strait, Cape Dezhnev, and Wrangel Island. </span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Russian%20Coast', 2, 'russian-coast', 1, 'Russian Coast'),
(6, 'Australia', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">Call it Earth’s largest island or smallest continent; what you can safely say is that Australia feels like a world of its own. The country’s immerse diversity—reflected in its landscapes, climates and endemic species—has long fascinated visitors. Add its cosmopolitan cities to the mix and it’s easy to see why this vast nation straddling the Indian and Pacific oceans is a must for any traveler’s bucket list. Cruise ships call at numerous Australian ports, including Sydney, Brisbane, Melbourne, Hobart and Darwin. And shore excursions or vacation packages will have you cuddling koalas, diving the Great Barrier Reef, and witnessing Aboriginal Dreamtime storytelling… to name just a few ways you’ll discover the Land Down Under.</span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Australia', 3, 'australia', 1, 'Australia'),
(7, 'New Zealand', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">If you found yourself fascinated by the dramatic scenery displayed on “The Lord of the Rings” and “The Hobbit” films, know that these lands don’t belong to mythical Middle Earth but to a country located closer to the ends of the Earth. Often overshadowed by its larger, more popular Oceanian neighbor (and we use that term loosely) Australia, New Zealand rewards travelers with breathtaking sceneries, endless stretches of beaches, and welcoming locals in a decidedly smaller package. One of only four countries to lie completely south of the Tropic of Capricorn, New Zealand consists of two distinct worlds: the subtropical, smaller yet more populous North Island, and the temperate, mountainous, and rugged South Island.</span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/New%20Zealand', 3, 'new-zealand', 1, 'New Zealand'),
(8, 'Africa - Middle East - India', '<p></p><p class="MsoNormal"><span style="font-size: 12pt; line-height: 107%; font-family: Arial, sans-serif; color: #282828; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Ancient Sanskrit literature used the word Ratnakara, “mine of gems,” to describe the massive body of water south of the Indian subcontinent. Although “Indian Ocean” is the common name nowadays, gems are still very much found throughout its shores.</span> </p><p class="MsoNormal"><span style="font-size: 12pt; line-height: 107%; font-family: Arial, sans-serif; color: #282828; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">From the coast of Cape Town in South Africa to the southeastern tip of Australia, the countries, regions, and cities that enclose the Indian Ocean form a vast, diverse, and fascinating network of cultures and landscapes. A cruise vacation or packaged tour to this region is a truly exotic journey into unfamiliar and remarkable lands.</span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Africa%20-%20Middle%20East%20-%20India', 2, 'africa-middle-east-india', 1, 'Africa, India and Middle East'),
(9, 'Southeast Asia', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">With beaches that can rival the best that Australia and the South Pacific have to offer, historical sites on par with those found in India, and cities every bit as vibrant and mesmerizing as the urban giants of East Asia, it’s tempting to think of Southeast Asia as a “greatest hits” of sorts of the vast Asia-Oceania region. After all, the French called this <em>Indochine,</em> relying on the fact that it’s located roughly between India and China. But that label feels like a disservice to the culturally rich and fiercely distinct nature of the nations that comprise Southeast Asia. Vietnam, Cambodia, Burma, Thailand, Malaysia, Singapore, Brunei, the Philippines, and Indonesia shine all with a light of their own, reflective of their native traditions and colonial experiences. </span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Southeast%20Asia', 2, 'southeast-asia', 1, 'Southeast Asia'),
(10, 'China - Japan - Korea', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">Millenary civilizations and ultramodern metropolises, ancient traditions and cutting-edge technology, peaceful shrines and bustling markets… ever straddling the line between familiar and exotic, East Asia offers a veritable yin yang of experiences and attractions. The countries of China, Japan, and Korea are treasure troves of fascinating cultures, stunning landscapes, historic sites, and world-famous cuisine. From the skyscrapers of Seoul and the hustle-and-bustle of Shanghai to the endless majesty of the Great Wall and the serenity of Kyoto’s Golden Pavilion, East Asia remains a must-visit destination. A cruise vacation or packaged trip to these countries offers travelers the chance to see and experience an unmatched array of wonders. </span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/China%20-%20Japan%20-%20Korea', 2, 'china-japan-korea', 1, 'China, Japan and Korea'),
(11, 'Bermuda', '<p>The island of Bermuda is a self-governing British territory which is composed of seven main islands and more than 150 rocks and islets.</p>', 'http://www.redhotcruiseplanners.com/subregions/view/Bermuda', 4, 'bermuda', 1, 'Bermuda'),
(12, 'Canary Islands', '<p></p><p><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif; mso-fareast-font-family: Calibri; mso-fareast-theme-font: minor-latin; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">Legend has it that the Canary Islands are the only remnants of the long-lost kingdom of Atlantis. What’s certainly not a myth is that this Spanish archipelago located off the southwestern coast of Morocco, Africa has long attracted visitors, thanks to its pleasant weather, enchanting locals, striking landscapes, alluring culture and, of course, abundance of beaches. The seven main islands of the archipelago—Gran Canaria, Tenerife, Lanzarote, Fuerteventura, La Palma, La Gomera, and El Hierro – welcome travelers with their distinctive charms</span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Canary%20Islands', 6, 'canary-islands', 1, 'Canary Islands'),
(13, 'North Europe', '<p></p><p><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif; mso-fareast-font-family: Calibri; mso-fareast-theme-font: minor-latin; mso-ansi-language: EN-US; mso-fareast-language: EN-US; mso-bidi-language: AR-SA;">From the elaborate system of canals and waterways in Amsterdam to the intriguing geothermal-rich sceneries of Iceland, discovering northern Europe is a treat for all the senses. Some of Europe’s most cosmopolitan and historic cities lie in this region, along with the most extreme and striking landscapes the continent has to offer. Covering the Netherlands, northern Germany, Denmark, Norway, the Faroe Islands, and Iceland, northern Europe provides a worthy destination alternative to Europe’s warmer zones</span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/North%20Europe', 6, 'north-europe', 1, 'North Europe'),
(14, 'European Coast', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">Standing at the western edge of the continent, the Atlantic coasts of Europe have served throughout history as the access points to the riches of the Old World and the gateway to New Worlds. Washing the shores of Portugal, Spain, France, and Belgium, these very coasts have witnessed Viking invasions, intrepid explorers in search of routes to Asia and the Americas, and the turning point in the fortunes of World War II. Shaped by the elements and the customs of the diverse cultures that call this region home, the European Coast offers a fascinating microcosm of the continent; one that’s rich in history, art, dramatic landscapes, first-rate cuisine, and charming cities.</span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/European%20Coast', 6, 'european-coast', 1, 'European Coast'),
(15, 'Norwegian Fjords', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">Norse mythology regarded fjords as gifts from the gods. Although nowadays it is widely accepted that glacial erosion is responsible for creating them, it’s hard to blame anyone for attributing a divine origin to these stunning natural landmarks. Striking waterfalls plummeting down rocky cliffs surrounded by thick forests and verdant meadows, colorful villages on the shores of cobalt-blue waters, and majestic glaciers defiantly cutting through the landscape paint the typical postcard beauty of this Scandinavian nation. More than a thousand fjords carve the coasts of Norway, from the southwestern ends of the country to the frigid reaches past the Arctic Circle.</span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Norwegian%20Fjords', 6, 'norwegian-fjords', 1, 'Norwegian Fjords'),
(16, 'Baltic Sea', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">An increasingly popular travel alternative to the Mediterranean, the Baltic Sea has benefitted from the gradual opening of former Soviet Republics as well as the Scandinavian destinations that have always been mainstays in the region. Enclosed by the shores of Sweden, Denmark, Finland, Germany, Poland, Latvia, Lithuania, Estonia, and Russia, this historically vital waterway has long held strategic importance and prominence in northern Europe. For tourists, it provides a maritime highway to discover the riches of this beautiful and diverse corner of the world. </span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Baltic%20Sea', 6, 'baltic-sea', 1, 'Baltic Sea'),
(17, 'Trans-Atlantic', '<p>For the traveler that simply wants to escape from the ordinary routine, nothing beats Trans Atlantic cruises. From six days to two weeks or more, the Trans Atlantic cruises crossing between Europe and America feature leisurely days at sea, rather than the usual series of port calls.\n<br><br>\nTrans Atlantic cruises once were the heart of daily commerce across the Atlantic, but today they are seasonal treats. Most Trans Atlantic cruises sail from the Caribbean to Europe and the Mediterranean in the spring and the return voyages in the fall.\n<br><br>\nEastbound Trans Atlantic cruises frequently depart from New York, Boston, Miami, Ft. Lauderdale and a few Caribbean ports. Westbound ships often sail from Southampton, England; Barcelona, Spain; and other major European port cities. Trans Atlantic cruises may take a longer, slower southern route past the Canary Islands, or the shorter and quicker northern course.\n<br>\nWhile a few of these cruises include visits to ports along the way - such as the Canary Islands or Iceland, the unique character of Trans Atlantic cruises make these short diversions from the main event, the voyage across the vast Atlantic Ocean.</p>', 'http://www.redhotcruiseplanners.com/subregions/view/Trans-Atlantic', 12, 'trans-atlantic', 0, 'Trans-Atlantic'),
(18, 'World Cruise (Exotic)', '<p>World Cruise: The luxury of choice and flexibility offered on destination-rich segment cruises or indulge in the grandest, most memorable adventure of all, a full world or grand cruise.</p>', 'http://www.redhotcruiseplanners.com/subregions/view/World%20Cruise%20%28Exotic%29', 12, 'world-cruise-exotic', 0, 'World Cruise (Exotic)'),
(19, 'Trans-Pacific', '<p>Trans Pacific cruises represent many different sailing options. Enjoy the Pacific Northwest and Japan in ten days sailing across the north Pacific. Or, take a longer trip aboard Trans Pacific Cruises across the southern Pacific from Los Angeles and visit Hawaii, Tahiti, Fiji, New Caledonia and Australia. Want to visit China, or New Zealand, or to sun in Mexico, or to shop in Seattle? Trans Pacific cruises visit a variety of ports and can last from ten to thirty-four days. Where you choose to sail on Trans Pacific cruises and for how long, is up to you.</p>', 'http://www.redhotcruiseplanners.com/subregions/view/Trans-Pacific', 12, 'trans-pacific', 0, 'Trans-Pacific'),
(20, 'Russian Rivers', '<p>As you embark on Russia\'s rivers, her great landmarks and welcoming heartland will mystify. Cruises in Russia give you the chance to take in the colorful sights of Red Square, the royal retreats of St. Petersburg and quaint Golden Ring towns like Yaroslavl and Uglich.</p>', 'http://www.redhotcruiseplanners.com/subregions/view/Russian%20Rivers', 11, 'russian-rivers', 1, 'Russian Rivers'),
(21, 'U.S. Rivers', '<p>In the US, river cruising can involve a voyage down the Mississippi River on a historic paddleboat, meandering alongside glaciers in Alaska or heading down the Hudson River on ships that carry fewer than 150 passengers and move at a relaxed pace.</p>', 'http://www.redhotcruiseplanners.com/subregions/view/U.S.%20Rivers', 11, 'us-rivers', 1, 'U.S. Rivers'),
(22, 'Chinese Rivers', '', 'http://www.redhotcruiseplanners.com/subregions/view/Chinese%20Rivers', 11, 'chinese-rivers', 1, 'Chinese Rivers'),
(23, 'European Rivers', '<p>Europe is a perfect blend of the ancient and the modern. Enjoy the timeless beauty and grace of the Old World with European river cruises along the Rhine, the Main, the Danube and the Seine. European river cruises will provide you with an unforgettable journey along these great waterways.</p>', 'http://www.redhotcruiseplanners.com/subregions/view/European%20Rivers', 11, 'european-rivers', 1, 'European Rivers'),
(24, 'Panama Canal', '<p>The Panama Canal was constructed more than 80 years ago,  but it is still a marvel of engineering.  The canal is 51 miles long with locks that raise a ship 85 feet at the Continental Divide and return to sea level in Caribbean Sea or Pacific Ocean.</p>', 'http://www.redhotcruiseplanners.com/subregions/view/Panama%20Canal', 10, 'panama-canal', 1, 'Panama Canal'),
(25, 'Mexico - Round Trip', '<p></p><p><span style="font-family: Arial, sans-serif; font-size: 12pt;">The Pacific coast of Mexico has been a tourist playground for decades. The seaside cities of Puerto Vallarta, Cabo San Lucas, Mazatlán, and Manzanillo offer visitors a plethora of beachfront resorts, outstanding watersports, and diverse natural landscapes that range from idyllic beach to lush tropical jungle to the volcanic peaks of the Sierra Madre mountains. Sailing from California, a packaged vacation or round-trip cruise to Mexico will introduce you to the rugged natural beauty of Baja California, the cultural richness of Jalisco, and myriad postcard-perfect beaches.</span><span style="font-family: Arial, sans-serif; font-size: 12pt;"> </span>.</p>', 'http://www.redhotcruiseplanners.com/subregions/view/Mexico%20-%20Round%20Trip', 9, 'mexico-round-trip', 0, 'Mexico - Round Trip'),
(26, 'Mexico - Baja', '<p></p><p><span style="font-family: Arial, sans-serif; font-size: 12pt;">Sandwiched between the Pacific and the Sea of Cortez, Baja California is a peninsula along the west coast of Mexico that stretches for almost 800 miles across desert and mountain, between sea and ocean. This incredible expanse is divided into two states—Baja Sur and Baja Norte—connected by the Trans peninsular Highway (Highway 1). This route is considered one of the great road trips in the U.S. (and who doesn’t like road trips!) for its spectacular scenery, isolated stretches, and the cattle that sometimes meander along the road with you. Famous for its wine, beaches, marine life, and get-away-from-it-all vibe, Baja sends its siren call to free spirits around the world.</span>.</p>', 'http://www.redhotcruiseplanners.com/subregions/view/Mexico%20-%20Baja', 9, 'mexico-baja', 1, 'Baja Mexico'),
(27, 'Mexico', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">Easily accessible and welcoming, Mexico offers virtually unlimited vacation options for travelers. The country is comprised of 31 states and one Federal District (Distrito Federal, or D.F.), spread out across a vast and diverse territory that ranges from arid desert in the on a cruise to Mexico, you can lie on a sun-kissed beach, indulge in all types of watersports, explore historic ruins, and dine like a cacique (a Mayan chieftain). The vaunted nightlife of Cancun, Puerto Vallarta, and other coastal cities will keep you up all night. And eco adventures abound, from nature parks to wildlife sanctuaries to wine tours in Baja, California.</span></p><p> </p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">If you want a more urban getaway, there are few metropolises in the world to compare with Mexico City. Colorful Guadalajara will invite you to hop on a tequila tasting tour, walk the beautiful city center and take in the mural art and colonial architecture, or test your palette on a culinary tour. In Oaxaca, you can tour the ancient city of Monte Alban, visit beautiful churches and cathedrals, and sample mole in street markets. The states of Palenque and Campeche offer plenty of outdoor adventure, with spectacular ruins like Palenque nestled in the jungle.</span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Mexico', 9, 'mexico', 1, 'Mexico'),
(28, 'Mediterranean', '<p>The Mediterranean Sea, a sea of myth and legend, is the largest inland sea. It is south of Europe, north of Africa, and west of Asia. It connects to the Atlantic Ocean through the Strait of Gibraltar, and to the Black Sea, the Sea of Marmara, and the Red Sea.<br><br>\nAncient civilizations flourished around the Mediterranean Sea. Later, the Mediterranean linked Europe, Africa and Asia as a major water highway for trade by merchants. After the building of the Suez Canal in 1869 it became, yet again, a major link between Europe and the Far East. \n\n</p>', 'http://www.redhotcruiseplanners.com/subregions/view/Mediterranean', 8, 'mediterranean', 1, 'Mediterranean'),
(29, 'Suez Canal', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">Built in 1869 to provide maritime access between the Mediterranean Sea and the Indian Ocean, the Suez Canal is truly one of mankind’s greatest feats of engineering and an unparalleled route to discover the riches of the Red Sea. Stretching for 100 miles across Egypt’s Sinai Peninsula, numerous cruise itineraries traverse it to reach countries such as Jordan, Saudi Arabia, Oman, United Arab Emirates, and Qatar. Ports of call around the region include Port Said, Aqaba, Safaga, and Sharm El-Sheikh. And for travelers who enjoy historical wonders, this region boasts some of the world’s most precious and awe-inspiring ancient sites.</span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Suez%20Canal', 8, 'suez-canal', 1, 'Suez Canal'),
(30, 'Holy Lands', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">Throughout the centuries, pilgrims have flocked to the Holy Lands mentioned in the Old and New Testaments to worship, pray, and trace the origins of their faith. The Holy Lands encompass Israel, Palestine, Jordan, and Egypt’s Sinai Peninsula, allowing visitors to craft a cruise itinerary, vacation package, or tour that covers numerous destinations and sights. Cruises call at various ports throughout this region, including Haifa, Beirut, and Ashdod. </span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Holy%20Lands', 8, 'holy-lands', 1, 'Holy Lands'),
(31, 'Black Sea', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">Accessible from the Mediterranean Sea via the Bosphorus and Dardanelles Strait, the Black Sea provides a road less traveled yet teeming with scenic and historical attractions. Each of the six countries that border its waters—Turkey, Georgia, Russia, Ukraine, Romania, and Bulgaria—offers unique experiences in tune with the area’s status as the crossroads between Europe and Asia. Cruises call at various ports throughout the Black Sea, including Istanbul, Trabzon, Sochi, Batumi, Yalta, Odessa, and Constan?a.</span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Black%20Sea', 8, 'black-sea', 1, 'Black Sea'),
(32, 'Mediterranean - Eastern', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">Far from taking a backseat to its western counterpart, the Eastern Mediterranean is quickly becoming one of Europe’s premier cruise destinations and holiday options. Many of Europe’s most prized ancient sites fall within its borders, as well as a slew of unique cities, intriguing landscapes and, of course, idyllic beaches. The region generally encompasses the Adriatic coasts of Italy, Croatia, Montenegro, and Albania; Greece and the Aegean Sea; Cyprus; and the Mediterranean coasts of Turkey. </span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Mediterranean%20-%20Eastern', 8, 'mediterranean-eastern', 1, 'Eastern Mediterranean'),
(33, 'Mediterranean - Western', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">Few regions in the world combine the sights, attractions, facilities, and overall charm of the Western Mediterranean. Generally defined as the coastal and insular regions of Spain, France, and Italy, cruise ships will often also include stops in Malta, Morocco, Tunisia, Gibraltar, and Portugal. Needless to say, the ports of call are as diverse as they are alluring, with cities like Barcelona, Marseilles, Nice, Cannes, Genoa, Florence (La Spezia), Naples, and Rome (Civitavecchia) on the list. Alone, any of these destinations make for an unforgettable vacation. Together, they represent one of the most celebrated and enviable combinations of manmade and natural beauty on the planet.  </span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Mediterranean%20-%20Western', 8, 'mediterranean-western', 1, 'Western Mediterranean'),
(34, 'South Pacific', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">When it comes to true escapes, few places can match the allure of the South Pacific. The beauty of the impossibly crystal-clear waters, picturesque white sands, and jaw-dropping island scenery is accentuated by the remote nature of this corner of the globe, giving visitors a sense of seclusion often associated with paradise. The region is loosely comprised of some 7,500 islands scattered throughout a massive stretch of the Pacific Ocean, and only 500 of these are inhabited. </span></p><p> </p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">In broad terms, the islands are divided among three groups: Melanesia, comprised of Papua New Guinea, Vanuatu, Solomon Islands, Fiji, and New Caledonia; Micronesia, home to the Caroline Islands, Marshall Islands, Gilbert Islands, and Mariana Islands; and the vast Polynesia—also called South Sea Islands—which includes Samoa, Tokelau, French Polynesia, Tonga, Tuvalu, and the Cook Islands, among others.</span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/South%20Pacific', 7, 'south-pacific', 1, 'South Pacific'),
(35, 'Hawaiian Islands', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">Despite being the 50<sup>th</sup> U.S. state, Hawaii rightfully feels worlds away; after all, the closest mainland cities are some five hours away by plane. Geographically considered the northeast corner of Polynesia, this volcanic archipelago in the middle of the Pacific Ocean has long been a magnet for tourism. Six of the state’s eight major islands are open to tourism: Hawaii, Oahu, Maui, Kauai, Molokai, and Lanai. The westernmost island of Niihau is privately owned, while tiny Kahoolawe is uninhabited. Many cruises to Hawaii let you island-hop, giving you the chance to pick out your favorite slice of paradise.</span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Hawaiian%20Islands', 7, 'hawaiian-islands', 1, 'Hawaiian Islands'),
(36, 'British Isles', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">In the British Isles, you’re never more than 70 miles away from the nearest shore, a perfect reason to discover this slice of Europe aboard a cruise ship. Comprised of Great Britain, Ireland, and numerous offshore islands (including the Isle of Man, the Channel Islands, the Orkney Isles, the Outer Hebrides, and the Shetland Isles), this region is home to England, Scotland, Wales, Northern Ireland, and the Republic of Ireland. Rich in culture and history, beautiful landscapes, breathtaking castles, and world-class cities, the British Isles offer a varied cruise experience for travelers of all interests. </span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/British%20Isles', 6, 'british-isles', 1, 'British Isles'),
(37, 'Caribbean - Extended', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">The Caribbean might sound like one homogenous collection of islands to many tourists, but anyone who’s been to its disparate countries and territories knows that numerous cultures, cuisines, landscapes, and experiences can be found among its crystal-clear waters. The region is comprised of 28 independent countries and dependent territories. A notorious pirate haunt for centuries, the Caribbean was the Wild West of the Old World for centuries, and was long coveted by its monarchs. To this day, the English, French, and Dutch have footholds here. The Spanish would have as well, were it not for the U.S., but their 300-year rule in these lands can still be felt in Puerto Rico, Cuba, Dominican Republic, and Mexico.  </span></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">It’s almost impossible to describe the Caribbean as a whole (unless “sunny with plenty of beaches” counts as a description!). And for many travelers, it’s equally difficult to choose one Caribbean destination. Do you want the colonial charms of Old San Juan in Puerto Rico or the pink-sand beaches of the Bahamas? Do you prefer the picturesque waterfalls of Jamaica or the shipwrecks off Cayman Islands? </span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Caribbean%20-%20Extended', 5, 'caribbean-extended', 0, 'Caribbean - Extended'),
(38, 'Caribbean - Southern', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">By being farther from the U.S. mainland, the islands in the Southern Caribbean tend to be the road less traveled in this tropical region. Places such as Martinique, Dominica, St. Lucia, Barbados, Trinidad and Tobago, Grenada, St. Vincent, and the Grenadines or the ABC islands (Aruba, Bonaire, and Curacao) retain a more exotic feel than other Caribbean destinations. These islands are also incredibly diverse, ranging from mountainous tropical wonderlands covered in lush rainforests to windswept, rocky havens with beaches that will remind you why you came to the Caribbean.</span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Caribbean%20-%20Southern', 5, 'caribbean-southern', 1, 'Southern Caribbean'),
(39, 'Caribbean - Western', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">With an alluring blend of ancient civilizations, eco-adventures, unparalleled diving sites, and plenty of sun, sand, and surf, the Western Caribbean is a natural magnet for travelers. The fact that it’s the closest region of the Caribbean to the mainland U.S. certainly helps as well. Loosely defined as the Caribbean coasts of Mexico, Belize, and Honduras, as well as the Cayman Islands and Jamaica, the destinations here offer a diverse and always enriching experience.</span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Caribbean%20-%20Western', 5, 'caribbean-western', 1, 'Western Caribbean'),
(40, 'Caribbean - Eastern', '<p></p><p class="MsoNormal"><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">Bustling ports brimming with activity and duty-free delights, crystal-clear beaches a stone’s throw away from the docks, island after island of pure tropical bliss… the Eastern Caribbean is arguably the world’s most cruise-friendly region, and its most popular destination for those in search of sun, sand, and R&amp;R. Cruise lines of all sizes and budgets offer itineraries that either remain solely within these waters or include one or more of its ports of call. With Puerto Rico serving as the Eastern Caribbean’s main travel hub, the region is usually defined as including the U.S. Virgin Islands, British Virgin Islands, St. Martin, Anguilla, St. Barth’s, Saint Eustatius, Saint Kitts and Nevis, and Antigua and Barbuda.</span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Caribbean%20-%20Eastern', 5, 'caribbean-eastern', 1, 'Eastern Caribbean'),
(41, 'Bahamas', '<p></p><p><span style="font-family: Cambria, serif;"><span style="font-size: 16px;">The azure allure of The Bahamas has attracted hordes of visitors for centuries. A mere 50 miles from the coast of Florida, this archipelago in the Caribbean has more than 700 islands and is known for its pristine beaches, watersports such as boating and fishing, duty-free shopping and colorful culture. As cruise ships call year-round at Nassau, Freeport, and a host of secluded private islands, anytime is a good time to visit the islands of The Bahamas. There are many family-friendly resorts, romantic bungalows, and private villas available for travelers looking for a quick getaway from the U.S</span></span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Bahamas', 5, 'bahamas', 1, 'Bahamas'),
(42, 'World Cruise', NULL, NULL, 12, 'world-cruise', 0, 'World Cruise'),
(43, 'U.S. East Coast', NULL, NULL, 13, 'us-east-coast', 1, 'U.S. East Coast'),
(44, 'Canada - New England', NULL, NULL, 13, 'canada-new-england', 1, 'Canada and New England'),
(45, 'South American Coast', NULL, NULL, 14, 'south-american-coast', 1, 'South American Coast'),
(46, 'Galapagos Islands', NULL, NULL, 14, 'galapagos-islands', 1, 'Galapagos Islands'),
(47, 'U.S. West Coast', NULL, NULL, 15, 'us-west-coast', 1, 'U.S. West Coast'),
(48, 'Cruise To Nowhere', NULL, NULL, 16, 'cruise-to-nowhere', 0, 'Cruise To Nowhere'),
(49, 'Caribbean - All', NULL, NULL, 5, 'caribbean-all', 1, 'Caribbean'),
(50, 'Central America', NULL, NULL, 14, 'central-america', 1, 'Central America'),
(51, 'Amazon River', NULL, NULL, 14, 'amazon-river', 1, 'Amazon River'),
(52, 'Repositioning', NULL, NULL, 17, 'repositioning', 0, 'Repositioning'),
(53, 'Antarctica & Arctica', NULL, NULL, 14, 'antarctica-arctica', 1, 'Antarctica and Arctica'),
(54, 'Eastern Canada', NULL, NULL, 13, 'eastern-canada', 1, 'Eastern Canada'),
(55, 'Unknown', NULL, NULL, 16, 'unknown', 0, 'Unknown'),
(56, 'Antarctica', '<p></p><p>Antarctica, fifth largest of the earth\'s seven continents, surrounds the South Pole. It is mostly circular and its total area is about 5.5-million sq. mi. in summer. During the winter Antarctica doubles in size because of the large amount of sea ice that forms at its periphery. The true boundary of Antarctica is not the coastline of the continent itself but the Antarctic Convergence.</p>', 'http://www.redhotcruiseplanners.com/subregions/view/Antarctica', 18, 'antarctica', 1, 'Antarctica'),
(57, 'Cuba', '<p></p><p class="MsoNormal"><span style="font-size: 12pt; line-height: 107%; font-family: Arial, sans-serif; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial;">Cuba is located in the northern Caribbean at the confluence of the Caribbean Sea, the Gulf of Mexico and the Atlantic Ocean. It is south of Florida and the Bahamas, west of Haiti and north of Jamaica. The largest and most intriguing of the Caribbean islands, Cuba is a unique place, perfect for the avid adventurer, where time-stood-still heritage has been captured. </span><span style="font-size: 12.0pt; line-height: 107%; font-family: \'Arial\',sans-serif;">Sugar from sugar cane is the main crop grown in Cuba, followed by tobacco which is used in the making of hand-crafted cigars that are famous for being the finest cigars in the world.</span></p>', 'http://www.redhotcruiseplanners.com/subregions/view/Cuba', 5, 'cuba', 1, 'Cuba');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
