# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active_depart', models.BooleanField(default=1, verbose_name=b'Active for departure')),
                ('is_active_destination', models.BooleanField(default=1, verbose_name=b'Active for destination')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='CruiseLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('is_active_depart', models.BooleanField(default=1, verbose_name=b'Active for departure')),
                ('is_active_destination', models.BooleanField(default=1, verbose_name=b'Active for destination')),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Country')),
            ],
            options={
                'verbose_name_plural': 'ports',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('big_logo_src', models.CharField(blank=True, max_length=200, null=True)),
                ('small_logo_src', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('cruise_line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.CruiseLine')),
            ],
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, null=True)),
                ('is_active_destination', models.BooleanField(default=1, verbose_name=b'Active for destination')),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Region')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'SubRegion',
                'verbose_name_plural': 'SubRegions',
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('exported', models.BooleanField(default=0, verbose_name=b'Exported')),
            ],
            options={
                'verbose_name': 'Subscriptions',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('nights', models.IntegerField(default=0)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.SubRegion')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Ship')),
            ],
        ),
        migrations.CreateModel(
            name='TravelDates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('nights', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('depart_date', models.DateField(blank=True, max_length=200, null=True)),
                ('return_date', models.DateField(blank=True, max_length=200, null=True)),
                ('inside_price', models.FloatField(blank=True, null=True)),
                ('ocean_price', models.FloatField(blank=True, null=True)),
                ('balcony_price', models.FloatField(blank=True, null=True)),
                ('suite_price', models.FloatField(blank=True, null=True)),
                ('departure_port', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_port', to='backend.Port')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Ship')),
            ],
        ),
        migrations.CreateModel(
            name='TravelDatesPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('arrive_time', models.TimeField(blank=True, null=True)),
                ('return_time', models.TimeField(blank=True, null=True)),
                ('port', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Port')),
                ('travel_date', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.TravelDates')),
            ],
        ),
        migrations.AddField(
            model_name='traveldates',
            name='visited_ports',
            field=models.ManyToManyField(through='backend.TravelDatesPort', to='backend.Port'),
        ),
    ]
