# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 13:44
from __future__ import unicode_literals
import os

from django.db import migrations

def load_data_from_sql():
    dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    sql_statements = open(os.path.join(dir,'migrations/sql/cruises.sql'), 'r').read()
    return sql_statements

def delete_data_with_sql():
    return 'DELETE from stores_store;'

class Migration(migrations.Migration):



    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [

    ]
