# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-02 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190202_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveldates',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.SubRegion'),
        ),
    ]
