# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-03 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_traveldates_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='travels',
            field=models.ManyToManyField(through='backend.TravelDatesPort', to='backend.TravelDates'),
        ),
        migrations.AlterField(
            model_name='traveldates',
            name='departure_port',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departure_port', to='backend.Port'),
        ),
    ]
