# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-06 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0004_auto_20190203_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersSavedTravels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='traveldates',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userssavedtravels',
            name='travel_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.TravelDates'),
        ),
        migrations.AddField(
            model_name='userssavedtravels',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traveldates',
            name='travelUserSaved',
            field=models.ManyToManyField(through='backend.UsersSavedTravels', to=settings.AUTH_USER_MODEL),
        ),
    ]
