"""
Django settings for launchCodeDemo project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'p3e_xh%ohgad7di50d(zr!gkerv0uo!ca6&hb+&)2o*)n-+bk-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'floppyforms',
    'pure_pagination',


    'backend',
    'frontend',
)
FLOPPY_FORMS_USE_GIS = False
MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'launchCodeDemo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'frontend.custom_processor.filter',
            ],
        },
    },
]
#
# from django.conf.global_settings import TEMPLATE_CONTEXT_PROCESSORS as TCP
#
# TEMPLATE_CONTEXT_PROCESSORS = TCP + (
#     'django.core.context_processors.request',
#     'django.template.context_processors.media'
# )

WSGI_APPLICATION = 'launchCodeDemo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'launchCodeDemo',
        'USER' : 'root',
        'PASSWORD': 'root',
        'HOST': '127.0.0.1'
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR,'media/')
MEDIA_URL = '/media/'

# STATIC_ROOT = '/var/www/cruises/'
STATICFILES_DIRS = (
    # Put strings here, like "/home/html/static" or "C:/www/django/static".
    # Always use forward slashes, even on Windows.
    # Don't forget to use absolute paths, not relative paths.
    os.path.join(BASE_DIR,'launchCodeDemo/media/fonts/'),
    os.path.join(BASE_DIR,'launchCodeDemo/media/css/'),
    os.path.join(BASE_DIR,'launchCodeDemo/media/js/'),
    os.path.join(BASE_DIR,'launchCodeDemo/media/imgs/'),
    os.path.join(BASE_DIR,'launchCodeDemo/media/slick/'),
    os.path.join(BASE_DIR,'launchCodeDemo/media/slick/'),
    os.path.join(BASE_DIR,'media/'),
    #os.path.join(BASE_DIR,'media/'),
)

BASE_IMAGES_URL = 'https://cruiseplannersnet.com'

PAGINATION_SETTINGS = {
        'PAGE_RANGE_DISPLAYED': 5,
        'MARGIN_PAGES_DISPLAYED': 5,
}

OBJECTS_PER_PAGE = 25

LOGIN_URL = '/accounts/login/'

#Email Configuration
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'ebergolla@gmail.com'
EMAIL_HOST_PASSWORD = 'test'
EMAIL_USE_TLS = True
MAIL_USE_SSL = False